/* Auto-generated by scripts/update_followers.py on 2025-11-28T03:37:01.257258Z - DO NOT EDIT */
window.followersData = {
  "youtube": "138k",
  "twitch": "75.3k",
  "tiktok": "15.3k",
  "facebook": "8.6k",
  "instagram": "38.7k",
  "discord": "10.8k"
};
