/* Auto-generated by scripts/update_followers.py on 2025-11-17T03:50:03.083689Z - DO NOT EDIT */
window.followersData = {
  "YouTube": "?",
  "Twitch": "?",
  "TikTok": "?",
  "Facebook": "?",
  "Instagram": "?",
  "Discord": "10.8k"
};
