/* Auto-generated by scripts/update_followers.py on 2025-11-17T08:14:15.356411Z - DO NOT EDIT */
window.followersData = {
  "youtube": "130k",
  "twitch": "71.7k",
  "tiktok": "12.7k",
  "facebook": "8.5k",
  "instagram": "31.1k",
  "discord": "10.8k"
};
